<?php
/** Quality standards page. @package NorthSpecsLabs */
get_header();
?>
<section class="nsl-quality-hero"><div class="nsl-shell nsl-quality-hero__grid"><div><?php nsl_eyebrow( 'Quality framework', true ); ?><h1><?php esc_html_e( 'Confidence begins with the record.', 'north-specs-labs' ); ?></h1><p><?php esc_html_e( 'Our quality experience is designed to keep compound identity, lot documentation, storage expectations and responsible-use limitations connected from catalogue to laboratory.', 'north-specs-labs' ); ?><p><a class="nsl-button nsl-button--light" href="<?php echo esc_url( nsl_page_url( 'certificates-of-analysis', '/certificates-of-analysis/' ) ); ?>"><?php esc_html_e( 'Open the COA archive', 'north-specs-labs' ); ?><?php echo nsl_icon( 'arrow' ); ?></a></div><div class="nsl-assay-panel"><span>QUALITY / FRAMEWORK</span><div class="nsl-assay-panel__rings"><i></i><i></i><i></i><b>NSL</b></div><dl><div><dt>Scope</dt><dd>Identity • documentation • handling</dd></div><div><dt>Designation</dt><dd>Research Use Only</dd></div><div><dt>Market</dt><dd>Qualified research entities</dd></div></dl></div></div></section>

<section class="nsl-section"><div class="nsl-shell"><div class="nsl-section-heading"><div><?php nsl_eyebrow( 'Documentation pathway' ); ?><h2><?php esc_html_e( 'A connected quality experience', 'north-specs-labs' ); ?></h2><p><?php esc_html_e( 'The controls below describe our documentation workflow. A Certificate of Analysis reports specific results for its identified lot and should not be generalized to another lot.', 'north-specs-labs' ); ?></p></div></div><ol class="nsl-process"><li><span>01</span><div><h3><?php esc_html_e( 'Source review', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Material identity and supplier documentation are reviewed before catalogue release.', 'north-specs-labs' ); ?></p></div></li><li><span>02</span><div><h3><?php esc_html_e( 'Lot assignment', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Each supplied batch receives a traceable lot identifier connected to its records.', 'north-specs-labs' ); ?></p></div></li><li><span>03</span><div><h3><?php esc_html_e( 'Analytical record', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Available analytical documentation is associated with the specific lot it represents.', 'north-specs-labs' ); ?></p></div></li><li><span>04</span><div><h3><?php esc_html_e( 'Controlled presentation', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Labels and product pages communicate identity, mass and Research Use Only status.', 'north-specs-labs' ); ?></p></div></li><li><span>05</span><div><h3><?php esc_html_e( 'Research support', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Researchers can request supporting records using the product and lot identifiers.', 'north-specs-labs' ); ?></p></div></li></ol></div></section>

<section class="nsl-section nsl-section--muted"><div class="nsl-shell nsl-editorial-grid"><div><?php nsl_eyebrow( 'Reading the record' ); ?><h2><?php esc_html_e( 'What a batch document can and cannot tell you', 'north-specs-labs' ); ?></h2></div><div class="nsl-prose"><h3><?php esc_html_e( 'Identity and purity are distinct', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'A chromatographic purity result describes the proportion of detected components under the stated method. Identity evidence addresses whether the measured material is consistent with the named compound. Researchers should review the full report, method and limitations.', 'north-specs-labs' ); ?></p><h3><?php esc_html_e( 'Results belong to the listed lot', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'A document applies only to the batch identifier shown. Always compare the lot on the vial with the lot on the record before relying on it in laboratory planning.', 'north-specs-labs' ); ?></p><h3><?php esc_html_e( 'Documentation does not change intended use', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Analytical records do not make a research material suitable for clinical, diagnostic, therapeutic, human or veterinary use.', 'north-specs-labs' ); ?></p></div></div></section>
<?php get_footer(); ?>
