<?php
/** Dynamic reconstitution calculator. @package NorthSpecsLabs */
get_header();
?>
<section class="nsl-page-hero nsl-page-hero--calculator"><div class="nsl-shell nsl-page-hero__grid"><div><?php nsl_eyebrow( 'Interactive laboratory reference' ); ?><h1><?php esc_html_e( 'Peptide reconstitution calculator', 'north-specs-labs' ); ?></h1><p><?php esc_html_e( 'Convert vial mass, diluent volume and a researcher-selected target mass into concentration, liquid volume and insulin-syringe units.', 'north-specs-labs' ); ?></p></div><div class="nsl-ruo-note"><?php echo nsl_icon( 'flask' ); ?><span><strong><?php esc_html_e( 'Calculation, not a protocol', 'north-specs-labs' ); ?></strong><?php esc_html_e( 'This tool does not recommend a dose, route, frequency or use. Inputs must come from an approved laboratory protocol.', 'north-specs-labs' ); ?></span></div></div></section>

<section class="nsl-section"><div class="nsl-shell">
	<div class="nsl-calculator" data-reconstitution-calculator>
		<div class="nsl-calculator__inputs">
			<div class="nsl-calculator__title"><div><span>NSL / LAB TOOL 01</span><h2><?php esc_html_e( 'Calculation inputs', 'north-specs-labs' ); ?></h2></div><button type="button" data-calc-reset><?php esc_html_e( 'Reset', 'north-specs-labs' ); ?></button></div>
			<fieldset><legend><?php esc_html_e( 'Select syringe capacity', 'north-specs-labs' ); ?></legend><div class="nsl-option-grid nsl-option-grid--three"><label><input type="radio" name="syringe" value="30"><span><strong>0.3 ml</strong><small>30 units</small></span></label><label><input type="radio" name="syringe" value="50"><span><strong>0.5 ml</strong><small>50 units</small></span></label><label><input type="radio" name="syringe" value="100" checked><span><strong>1.0 ml</strong><small>100 units</small></span></label></div></fieldset>
			<div class="nsl-calc-field"><label for="nsl-peptide-mg"><?php esc_html_e( 'Compound amount', 'north-specs-labs' ); ?></label><div class="nsl-input-with-unit"><input id="nsl-peptide-mg" data-calc-peptide type="number" min="0.01" step="0.01" value="10" inputmode="decimal"><span>mg</span></div><div class="nsl-preset-row" data-target="nsl-peptide-mg"><?php foreach ( array( 2, 5, 10, 15, 20, 30 ) as $value ) : ?><button type="button" data-value="<?php echo esc_attr( (string) $value ); ?>"><?php echo esc_html( (string) $value ); ?></button><?php endforeach; ?></div></div>
			<div class="nsl-calc-field"><label for="nsl-water-ml"><?php esc_html_e( 'Diluent volume', 'north-specs-labs' ); ?></label><div class="nsl-input-with-unit"><input id="nsl-water-ml" data-calc-water type="number" min="0.01" step="0.01" value="2" inputmode="decimal"><span>ml</span></div><div class="nsl-preset-row" data-target="nsl-water-ml"><?php foreach ( array( 1, 2, 3, 5 ) as $value ) : ?><button type="button" data-value="<?php echo esc_attr( (string) $value ); ?>"><?php echo esc_html( (string) $value ); ?></button><?php endforeach; ?></div></div>
			<div class="nsl-calc-field"><label for="nsl-target-mcg"><?php esc_html_e( 'Target mass per sample', 'north-specs-labs' ); ?></label><div class="nsl-input-with-unit"><input id="nsl-target-mcg" data-calc-dose type="number" min="0.01" step="0.01" value="250" inputmode="decimal"><span>mcg</span></div><div class="nsl-preset-row" data-target="nsl-target-mcg"><?php foreach ( array( 50, 100, 250, 500, 1000 ) as $value ) : ?><button type="button" data-value="<?php echo esc_attr( (string) $value ); ?>"><?php echo esc_html( (string) $value ); ?></button><?php endforeach; ?></div></div>
		</div>

		<div class="nsl-calculator__visual">
			<p class="nsl-calculator__pull-label"><?php esc_html_e( 'Calculated syringe mark', 'north-specs-labs' ); ?></p><p class="nsl-calculator__units"><strong data-result-units>5.00</strong><span>units</span></p><p class="nsl-calculator__volume"><span data-result-volume>0.050</span> ml</p>
			<div class="nsl-syringe-wrap">
				<svg class="nsl-syringe" viewBox="0 0 220 470" role="img" data-syringe aria-labelledby="nsl-syringe-title"><title id="nsl-syringe-title"><?php esc_html_e( 'Dynamic insulin syringe illustration', 'north-specs-labs' ); ?></title><defs><linearGradient id="nsl-glass" x1="0" x2="1"><stop stop-color="#fff"/><stop offset=".45" stop-color="#f7f4ed"/><stop offset="1" stop-color="#e1e7df"/></linearGradient><linearGradient id="nsl-liquid" x1="0" x2="1"><stop stop-color="#69ad85"/><stop offset="1" stop-color="#1b573a"/></linearGradient><clipPath id="nsl-barrel"><rect x="70" y="82" width="58" height="310" rx="5"/></clipPath></defs><path d="M99 9v42" stroke="#536459" stroke-width="3" stroke-linecap="round"/><path d="M86 50h26l-5 32H91z" fill="#d8eee1" stroke="#9aaa9d"/><rect x="70" y="82" width="58" height="310" rx="5" fill="url(#nsl-glass)" stroke="#9aaa9d" stroke-width="2"/><g clip-path="url(#nsl-barrel)"><rect class="nsl-syringe__liquid" data-syringe-liquid x="71" y="83" width="56" height="308" fill="url(#nsl-liquid)"/><rect x="78" y="83" width="5" height="308" fill="#fff" opacity=".28"/></g><rect class="nsl-syringe__seal" data-syringe-seal x="70" y="82" width="58" height="18" rx="3" fill="#2f3d33"/><path d="M99 100v330" stroke="#bcc8bc" stroke-width="13"/><path d="M61 438h76" stroke="#65776a" stroke-width="13" stroke-linecap="round"/><g class="nsl-syringe__ticks" data-syringe-ticks></g><g class="nsl-syringe__marker" data-syringe-marker><path d="M34 82h36" stroke="#b3936c" stroke-width="2" stroke-dasharray="4 3"/><rect x="7" y="68" width="53" height="28" rx="6" fill="#b3936c"/><text data-syringe-label x="33.5" y="87" text-anchor="middle" fill="#fff" font-size="11" font-weight="700">5.00</text></g></svg>
			</div>
			<div class="nsl-calc-warning" data-calc-warning hidden></div>
			<div class="nsl-result-grid"><div><span><?php esc_html_e( 'Concentration', 'north-specs-labs' ); ?></span><strong data-result-concentration>5.00</strong><small>mg/ml</small></div><div><span><?php esc_html_e( 'Per unit', 'north-specs-labs' ); ?></span><strong data-result-per-unit>50.0</strong><small>mcg</small></div><div><span><?php esc_html_e( 'Samples per vial', 'north-specs-labs' ); ?></span><strong data-result-doses>40.0</strong><small><?php esc_html_e( 'calculated', 'north-specs-labs' ); ?></small></div><div><span><?php esc_html_e( 'Selected capacity', 'north-specs-labs' ); ?></span><strong data-result-capacity>100</strong><small>units</small></div></div>
		</div>
	</div>

	<div class="nsl-calculator-notes"><section><span>01</span><div><h2><?php esc_html_e( 'Calculation model', 'north-specs-labs' ); ?></h2><p><?php esc_html_e( 'Concentration equals vial mass divided by diluent volume. Target mass is converted from micrograms to milligrams, divided by concentration to obtain millilitres, then multiplied by 100 for U-100 insulin-syringe units.', 'north-specs-labs' ); ?></p></div></section><section><span>02</span><div><h2><?php esc_html_e( 'Verify units independently', 'north-specs-labs' ); ?></h2><p><?php esc_html_e( 'A unit entry error can change the result by orders of magnitude. Qualified researchers should independently verify arithmetic, equipment calibration, material specifications and institutional procedures.', 'north-specs-labs' ); ?></p></div></section><section><span>03</span><div><h2><?php esc_html_e( 'Scope limitation', 'north-specs-labs' ); ?></h2><p><?php esc_html_e( 'The calculator is an educational mathematics tool for laboratory planning. It is not validated for clinical, diagnostic, therapeutic, human or veterinary use.', 'north-specs-labs' ); ?></p></div></section></div>
</div></section>
<?php get_footer(); ?>
