<?php
/** About page. @package NorthSpecsLabs */
get_header();
?>
<section class="nsl-page-hero nsl-page-hero--split"><div class="nsl-shell nsl-page-hero__grid"><div><?php nsl_eyebrow( 'About North Specs Labs' ); ?><h1><?php esc_html_e( 'Built for research teams that expect clarity.', 'north-specs-labs' ); ?></h1><p><?php esc_html_e( 'North Specs Labs is a Canadian research supply company focused on documented materials, responsible distribution and a transparent digital procurement experience.', 'north-specs-labs' ); ?></p></div><div class="nsl-specimen-card"><span>NSL / 01</span><strong><?php esc_html_e( 'Scientific discipline in every detail.', 'north-specs-labs' ); ?></strong><p><?php esc_html_e( 'From the product label to checkout attestation, every touchpoint reinforces responsible Research Use Only handling.', 'north-specs-labs' ); ?></p></div></div></section>

<section class="nsl-section"><div class="nsl-shell nsl-editorial-grid"><div><?php nsl_eyebrow( 'Our position' ); ?><h2><?php esc_html_e( 'Research supply should be accountable, not ambiguous.', 'north-specs-labs' ); ?></h2></div><div class="nsl-prose"><p><?php esc_html_e( 'We believe qualified researchers should be able to identify a compound, locate its supporting lot records, understand the handling expectations and complete an institutional order without navigating exaggerated consumer claims.', 'north-specs-labs' ); ?></p><p><?php esc_html_e( 'That principle shapes our catalogue, educational library and researcher account experience. North Specs products are supplied only for legitimate laboratory research and are never represented as medicines, treatments, foods, cosmetics or products for human or veterinary consumption.', 'north-specs-labs' ); ?></p></div></div></section>

<section class="nsl-section nsl-section--muted"><div class="nsl-shell"><div class="nsl-section-heading"><div><?php nsl_eyebrow( 'Operating principles' ); ?><h2><?php esc_html_e( 'What the North Specs standard means', 'north-specs-labs' ); ?></h2></div></div><div class="nsl-principle-grid"><article><span>01</span><h3><?php esc_html_e( 'Traceable', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Product and lot identifiers connect the physical vial to its digital records.', 'north-specs-labs' ); ?></p></article><article><span>02</span><h3><?php esc_html_e( 'Research-first', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Information is written for laboratory audiences and avoids consumer-use guidance.', 'north-specs-labs' ); ?></p></article><article><span>03</span><h3><?php esc_html_e( 'Transparent', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Limitations, policies and responsible-use requirements stay visible throughout the journey.', 'north-specs-labs' ); ?></p></article><article><span>04</span><h3><?php esc_html_e( 'Supported', 'north-specs-labs' ); ?></h3><p><?php esc_html_e( 'Researchers can reach a documentation-led support team before and after ordering.', 'north-specs-labs' ); ?></p></article></div></div></section>

<section class="nsl-section"><div class="nsl-shell nsl-editorial-cta"><div><?php nsl_eyebrow( 'Qualified researchers' ); ?><h2><?php esc_html_e( 'A better procurement experience starts with better information.', 'north-specs-labs' ); ?></h2><p><?php esc_html_e( 'Explore the catalogue, review our quality framework or speak with research support.', 'north-specs-labs' ); ?></p></div><div class="nsl-button-group"><a class="nsl-button" href="<?php echo esc_url( nsl_shop_url() ); ?>"><?php esc_html_e( 'Browse compounds', 'north-specs-labs' ); ?><?php echo nsl_icon( 'arrow' ); ?></a><a class="nsl-text-link" href="<?php echo esc_url( nsl_page_url( 'quality', '/quality/' ) ); ?>"><?php esc_html_e( 'View quality standards', 'north-specs-labs' ); ?><?php echo nsl_icon( 'arrow' ); ?></a></div></div></section>
<?php get_footer(); ?>
