import type { Category, Product, Variant } from "./types";

/**
 * Built-in demo catalogue.
 *
 * This powers the storefront out-of-the-box (no database required) and mirrors
 * `supabase/seed.sql`. Once Supabase is configured and seeded, live data from
 * the database takes over automatically — see `src/lib/data/*`.
 *
 * IDs are deterministic (slug / SKU) so links and the cart stay stable.
 */

export const demoCategories: Category[] = [
  {
    id: "metabolic-research",
    name: "Metabolic Research",
    slug: "metabolic-research",
    shortDescription: "Incretin and metabolic-signalling peptides for research.",
    description:
      "GLP-1, GIP and related incretin analogues studied for metabolic and endocrine signalling pathways. Supplied strictly for in-vitro and laboratory research.",
    icon: "activity",
    displayOrder: 1,
  },
  {
    id: "growth-hormone-secretagogues",
    name: "Growth Hormone Secretagogues",
    slug: "growth-hormone-secretagogues",
    shortDescription: "GHRH analogues and growth-hormone releasing peptides.",
    description:
      "Secretagogue peptides investigated for their action on the somatotropic axis. For laboratory research use only.",
    icon: "trending-up",
    displayOrder: 2,
  },
  {
    id: "tissue-repair-recovery",
    name: "Tissue Repair & Recovery",
    slug: "tissue-repair-recovery",
    shortDescription: "Peptides studied in tissue, connective and cellular repair models.",
    description:
      "Compounds frequently referenced in regenerative and cytoprotective research models. Research use only.",
    icon: "heart-pulse",
    displayOrder: 3,
  },
  {
    id: "longevity-cellular-health",
    name: "Longevity & Cellular Health",
    slug: "longevity-cellular-health",
    shortDescription: "Bioregulators and mitochondrial-signalling peptides.",
    description:
      "Peptides investigated in cellular ageing, telomere and mitochondrial research. Not for human or veterinary use.",
    icon: "infinity",
    displayOrder: 4,
  },
  {
    id: "neuro-cognitive",
    name: "Neuro & Cognitive",
    slug: "neuro-cognitive",
    shortDescription: "Neuropeptides studied in cognition and neuroprotection.",
    description:
      "Nootropic and neuroprotective peptides used in behavioural and neurological research models.",
    icon: "brain",
    displayOrder: 5,
  },
  {
    id: "bioregulation-signalling",
    name: "Bioregulation & Signalling",
    slug: "bioregulation-signalling",
    shortDescription: "Melanocortin, kisspeptin and signalling peptides.",
    description:
      "Signalling peptides studied across endocrine and receptor-pharmacology research. Research use only.",
    icon: "atom",
    displayOrder: 6,
  },
];

function variant(
  sku: string,
  name: string,
  sizeMg: number,
  priceCents: number,
  stockQuantity: number,
): Variant {
  return { id: sku, sku, name, sizeMg, priceCents, stockQuantity, isActive: true };
}

type RawProduct = Omit<Product, "id" | "variants" | "coas" | "researchUseOnly" | "categoryName"> & {
  variants: Variant[];
  coas?: Product["coas"];
};

const rawProducts: RawProduct[] = [
  {
    name: "Semaglutide",
    slug: "semaglutide",
    subtitle: "GLP-1 receptor agonist",
    categorySlug: "metabolic-research",
    casNumber: "910463-68-2",
    molecularFormula: "C187H291N45O59",
    molecularWeight: 4113.58,
    sequence: "HAEGTFTSDVSSYLEGQAAKEFIAWLVRGRG (modified)",
    purity: "≥99%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C, protect from light.",
    reconstitution:
      "Reconstitute with bacteriostatic or sterile water; keep refrigerated after reconstitution.",
    researchAreas: ["Metabolic signalling", "Endocrinology", "Incretin research"],
    description:
      "Semaglutide is a long-acting GLP-1 receptor agonist widely referenced in metabolic and incretin-signalling research. Supplied as a lyophilized powder for laboratory research applications only.",
    isFeatured: true,
    variants: [variant("NS-SEMA-05", "5 mg", 5, 8900, 120), variant("NS-SEMA-10", "10 mg", 10, 15900, 80)],
    coas: [{ id: "NS-SEMA-2607A", batchNumber: "NS-SEMA-2607A", purity: "99.4%", testMethod: "HPLC / MS", testDate: "2026-07-14" }],
  },
  {
    name: "Tirzepatide",
    slug: "tirzepatide",
    subtitle: "Dual GIP/GLP-1 receptor agonist",
    categorySlug: "metabolic-research",
    casNumber: "2023788-19-2",
    molecularFormula: "C225H348N48O68",
    molecularWeight: 4813.53,
    sequence: "YXEGTFTSDYSIXLDKIAQKAFVQWLIAGGPSSGAPPPS (modified)",
    purity: "≥99%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C, protect from light.",
    reconstitution:
      "Reconstitute with bacteriostatic or sterile water; keep refrigerated after reconstitution.",
    researchAreas: ["Metabolic signalling", "Dual incretin research", "Endocrinology"],
    description:
      "Tirzepatide is a dual GIP and GLP-1 receptor agonist studied extensively in incretin-pathway research. For in-vitro / laboratory research use only.",
    isFeatured: true,
    variants: [variant("NS-TIRZ-10", "10 mg", 10, 16900, 90), variant("NS-TIRZ-15", "15 mg", 15, 22900, 60)],
    coas: [{ id: "NS-TIRZ-2606B", batchNumber: "NS-TIRZ-2606B", purity: "99.1%", testMethod: "HPLC / MS", testDate: "2026-06-28" }],
  },
  {
    name: "Retatrutide",
    slug: "retatrutide",
    subtitle: "Triple GIP/GLP-1/glucagon agonist",
    categorySlug: "metabolic-research",
    casNumber: "2381089-83-2",
    molecularFormula: "C221H346N46O66",
    molecularWeight: 4731.3,
    sequence: "Multi-agonist analogue",
    purity: "≥99%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C, protect from light.",
    reconstitution:
      "Reconstitute with bacteriostatic or sterile water; keep refrigerated after reconstitution.",
    researchAreas: ["Triple-agonist research", "Metabolic signalling"],
    description:
      "Retatrutide is a triple receptor agonist (GIP/GLP-1/glucagon) referenced in advanced metabolic-signalling studies. Research use only.",
    isFeatured: true,
    variants: [variant("NS-RETA-10", "10 mg", 10, 19900, 50)],
  },
  {
    name: "Tesamorelin",
    slug: "tesamorelin",
    subtitle: "GHRH analogue",
    categorySlug: "metabolic-research",
    casNumber: "218949-48-5",
    molecularFormula: "C221H366N72O67S",
    molecularWeight: 5135.87,
    sequence: "YAEGTFTSDYSKYLDKMHTHTHTHTHTH",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic water; refrigerate after reconstitution.",
    researchAreas: ["Somatotropic axis", "Lipid metabolism research"],
    description:
      "Tesamorelin is a stabilised GHRH analogue used in endocrine and metabolic research models. Research use only.",
    isFeatured: false,
    variants: [variant("NS-TESA-10", "10 mg", 10, 13900, 40)],
  },
  {
    name: "AOD-9604",
    slug: "aod-9604",
    subtitle: "hGH fragment 176-191",
    categorySlug: "metabolic-research",
    casNumber: "221231-10-3",
    molecularFormula: "C78H123N23O23S2",
    molecularWeight: 1815.08,
    sequence: "YLRIVQCRSVEGSCGF",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["Lipid metabolism research", "hGH fragment studies"],
    description:
      "AOD-9604 is a modified fragment of human growth hormone (176-191) studied in lipid-metabolism research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-AOD-05", "5 mg", 5, 6900, 70)],
  },
  {
    name: "MOTS-c",
    slug: "mots-c",
    subtitle: "Mitochondrial-derived peptide",
    categorySlug: "longevity-cellular-health",
    casNumber: "1627580-64-6",
    molecularFormula: "C101H152N28O23S2",
    molecularWeight: 2174.55,
    sequence: "MRWQEMGYIFYPRKLR",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["Mitochondrial research", "Cellular metabolism"],
    description:
      "MOTS-c is a mitochondrial-derived peptide investigated in metabolic and cellular-stress research. Research use only.",
    isFeatured: true,
    variants: [variant("NS-MOTS-10", "10 mg", 10, 9900, 55)],
  },
  {
    name: "CJC-1295 with DAC",
    slug: "cjc-1295-dac",
    subtitle: "Long-acting GHRH analogue",
    categorySlug: "growth-hormone-secretagogues",
    casNumber: "863288-34-0",
    molecularFormula: "C165H269N47O46",
    molecularWeight: 3647.19,
    sequence: "Modified GRF (1-29) with DAC",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic water; refrigerate after reconstitution.",
    researchAreas: ["Somatotropic axis", "GHRH research"],
    description:
      "CJC-1295 with DAC is a long-acting GHRH analogue used in somatotropic-axis research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-CJCD-05", "5 mg", 5, 7900, 65)],
  },
  {
    name: "Ipamorelin",
    slug: "ipamorelin",
    subtitle: "Selective GH secretagogue",
    categorySlug: "growth-hormone-secretagogues",
    casNumber: "170851-70-4",
    molecularFormula: "C38H49N9O5",
    molecularWeight: 711.85,
    sequence: "Aib-His-D-2-Nal-D-Phe-Lys-NH2",
    purity: "≥99%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["GH secretagogue research", "Ghrelin-receptor studies"],
    description:
      "Ipamorelin is a selective growth-hormone secretagogue and ghrelin-receptor agonist referenced in endocrine research. Research use only.",
    isFeatured: true,
    variants: [variant("NS-IPAM-10", "10 mg", 10, 7900, 110)],
    coas: [{ id: "NS-IPAM-2607B", batchNumber: "NS-IPAM-2607B", purity: "99.5%", testMethod: "HPLC / MS", testDate: "2026-07-09" }],
  },
  {
    name: "Sermorelin",
    slug: "sermorelin",
    subtitle: "GHRH (1-29)",
    categorySlug: "growth-hormone-secretagogues",
    casNumber: "86168-78-7",
    molecularFormula: "C149H246N44O42S",
    molecularWeight: 3357.93,
    sequence: "GRF (1-29)",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic water; refrigerate after reconstitution.",
    researchAreas: ["Somatotropic axis", "GHRH research"],
    description:
      "Sermorelin is a GHRH (1-29) analogue widely used in somatotropic-axis research models. Research use only.",
    isFeatured: false,
    variants: [variant("NS-SERM-05", "5 mg", 5, 7400, 60)],
  },
  {
    name: "Hexarelin",
    slug: "hexarelin",
    subtitle: "GH-releasing hexapeptide",
    categorySlug: "growth-hormone-secretagogues",
    casNumber: "140703-51-1",
    molecularFormula: "C47H58N12O6",
    molecularWeight: 887.02,
    sequence: "His-D-2-methyl-Trp-Ala-Trp-D-Phe-Lys-NH2",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["GH secretagogue research"],
    description:
      "Hexarelin is a synthetic growth-hormone releasing hexapeptide used in secretagogue research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-HEXA-05", "5 mg", 5, 6900, 45)],
  },
  {
    name: "BPC-157",
    slug: "bpc-157",
    subtitle: "Body Protection Compound",
    categorySlug: "tissue-repair-recovery",
    casNumber: "137525-51-0",
    molecularFormula: "C62H98N16O22",
    molecularWeight: 1419.53,
    sequence: "GEPPPGKPADDAGLV",
    purity: "≥99%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["Cytoprotection research", "Connective-tissue models", "Gastrointestinal research"],
    description:
      "BPC-157 is a synthetic pentadecapeptide referenced extensively in cytoprotective and tissue-repair research models. Research use only.",
    isFeatured: true,
    variants: [variant("NS-BPC-05", "5 mg", 5, 5900, 150), variant("NS-BPC-10", "10 mg", 10, 9900, 120)],
    coas: [{ id: "NS-BPC-2607C", batchNumber: "NS-BPC-2607C", purity: "99.7%", testMethod: "HPLC / MS", testDate: "2026-07-02" }],
  },
  {
    name: "TB-500",
    slug: "tb-500",
    subtitle: "Thymosin Beta-4 fragment",
    categorySlug: "tissue-repair-recovery",
    casNumber: "77591-33-4",
    molecularFormula: "C212H350N56O78S",
    molecularWeight: 4963.44,
    sequence: "Ac-SDKP (active region of Thymosin β4)",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["Actin-regulation research", "Tissue-repair models"],
    description:
      "TB-500 corresponds to the active region of Thymosin Beta-4 and is studied in actin-regulation and tissue-repair research. Research use only.",
    isFeatured: true,
    variants: [variant("NS-TB5-05", "5 mg", 5, 8900, 90), variant("NS-TB5-10", "10 mg", 10, 15900, 60)],
    coas: [{ id: "NS-TB5-2606A", batchNumber: "NS-TB5-2606A", purity: "98.9%", testMethod: "HPLC / MS", testDate: "2026-06-19" }],
  },
  {
    name: "GHK-Cu",
    slug: "ghk-cu",
    subtitle: "Copper tripeptide-1",
    categorySlug: "tissue-repair-recovery",
    casNumber: "89030-95-5",
    molecularFormula: "C14H24N6O4Cu",
    molecularWeight: 403.94,
    sequence: "Gly-His-Lys : Cu(II)",
    purity: "≥99%",
    appearance: "Blue lyophilized powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C, protect from light.",
    reconstitution: "Reconstitute with sterile water.",
    researchAreas: ["Dermatological research", "Copper-peptide studies"],
    description:
      "GHK-Cu is a copper-binding tripeptide widely referenced in skin, collagen and copper-peptide research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-GHK-50", "50 mg", 50, 6400, 80)],
  },
  {
    name: "Epithalon",
    slug: "epithalon",
    subtitle: "Telomerase-research tetrapeptide",
    categorySlug: "longevity-cellular-health",
    casNumber: "307297-39-8",
    molecularFormula: "C14H22N4O9",
    molecularWeight: 390.35,
    sequence: "Ala-Glu-Asp-Gly",
    purity: "≥99%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["Telomere research", "Pineal bioregulation"],
    description:
      "Epithalon (Epitalon) is a synthetic tetrapeptide studied in telomere and cellular-ageing research. Research use only.",
    isFeatured: true,
    variants: [variant("NS-EPI-10", "10 mg", 10, 6900, 75), variant("NS-EPI-50", "50 mg", 50, 17900, 30)],
  },
  {
    name: "Thymosin Alpha-1",
    slug: "thymosin-alpha-1",
    subtitle: "Immunomodulatory peptide",
    categorySlug: "longevity-cellular-health",
    casNumber: "62304-98-7",
    molecularFormula: "C129H215N33O55",
    molecularWeight: 3108.3,
    sequence: "Ac-SDAAVDTSSEITTKDLKEKKEVVEEAEN",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water.",
    researchAreas: ["Immunology research", "Cellular signalling"],
    description:
      "Thymosin Alpha-1 is a 28-amino-acid peptide studied in immunomodulation research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-TA1-05", "5 mg", 5, 9400, 40)],
  },
  {
    name: "Semax",
    slug: "semax",
    subtitle: "ACTH(4-10) analogue nootropic",
    categorySlug: "neuro-cognitive",
    casNumber: "80714-61-0",
    molecularFormula: "C37H51N9O10S",
    molecularWeight: 813.92,
    sequence: "Met-Glu-His-Phe-Pro-Gly-Pro",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with sterile or bacteriostatic water.",
    researchAreas: ["Neuroprotection research", "Cognition models"],
    description:
      "Semax is a synthetic ACTH(4-10) analogue used in neuroprotection and cognition research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-SMX-30", "30 mg", 30, 8900, 50)],
  },
  {
    name: "Selank",
    slug: "selank",
    subtitle: "Tuftsin-analogue anxiolytic peptide",
    categorySlug: "neuro-cognitive",
    casNumber: "129954-34-3",
    molecularFormula: "C33H57N11O9",
    molecularWeight: 751.9,
    sequence: "Thr-Lys-Pro-Arg-Pro-Gly-Pro",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with sterile or bacteriostatic water.",
    researchAreas: ["Anxiolytic research", "Neuropeptide studies"],
    description:
      "Selank is a synthetic analogue of tuftsin studied in anxiolytic and neuropeptide research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-SLK-10", "10 mg", 10, 7400, 50)],
  },
  {
    name: "PT-141",
    slug: "pt-141",
    subtitle: "Bremelanotide (melanocortin agonist)",
    categorySlug: "bioregulation-signalling",
    casNumber: "189691-06-3",
    molecularFormula: "C50H68N14O10",
    molecularWeight: 1025.16,
    sequence: "Ac-Nle-cyclo(Asp-His-D-Phe-Arg-Trp-Lys)-OH",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C.",
    reconstitution: "Reconstitute with sterile or bacteriostatic water.",
    researchAreas: ["Melanocortin-receptor research"],
    description:
      "PT-141 (Bremelanotide) is a melanocortin-receptor agonist referenced in receptor-pharmacology research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-PT1-10", "10 mg", 10, 6900, 65)],
  },
  {
    name: "Melanotan II",
    slug: "melanotan-ii",
    subtitle: "Melanocortin agonist",
    categorySlug: "bioregulation-signalling",
    casNumber: "121062-08-6",
    molecularFormula: "C50H69N15O9",
    molecularWeight: 1024.18,
    sequence: "Ac-Nle-cyclo(Asp-His-D-Phe-Arg-Trp-Lys)-NH2",
    purity: "≥98%",
    appearance: "Lyophilized white powder",
    form: "Lyophilized powder",
    storage: "Store lyophilized at -20°C, protect from light.",
    reconstitution: "Reconstitute with sterile or bacteriostatic water.",
    researchAreas: ["Melanocortin research", "Pigmentation models"],
    description:
      "Melanotan II is a synthetic melanocortin-receptor agonist used in pigmentation and receptor research. Research use only.",
    isFeatured: false,
    variants: [variant("NS-MT2-10", "10 mg", 10, 6400, 70)],
  },
];

const categoryNameBySlug = new Map(demoCategories.map((c) => [c.slug, c.name]));

export const demoProducts: Product[] = rawProducts.map((p) => ({
  ...p,
  id: p.slug,
  categoryName: p.categorySlug ? categoryNameBySlug.get(p.categorySlug) ?? null : null,
  researchUseOnly: true,
  coas: p.coas ?? [],
}));

export const demoCategoriesWithCounts: Category[] = demoCategories.map((c) => ({
  ...c,
  productCount: demoProducts.filter((p) => p.categorySlug === c.slug).length,
}));
